
version: '3'
services:
  hello-world-app:
      container-name: helloworldnodejs
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
        - 8082:3000  
